version: "3.9"

services:
  redis-node-1:
    image: redis:latest
    container_name: redis-node-1
    command:
      - redis-server
      - --cluster-enabled
      - "yes"
      - --cluster-config-file
      - /data/nodes.conf
      - --cluster-node-timeout
      - "5000"
      - --appendonly
      - "yes"
      - --port
      - "6379"
      - --dir
      - /data
    ports:
      - "6379:6379"
      - "16379:16379"
    volumes:
      - redis-node-1-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.2

  redis-node-2:
    image: redis:latest
    container_name: redis-node-2
    command:
      - redis-server
      - --cluster-enabled
      - "yes"
      - --cluster-config-file
      - /data/nodes.conf
      - --cluster-node-timeout
      - "5000"
      - --appendonly
      - "yes"
      - --port
      - "6379"
      - --dir
      - /data
    ports:
      - "6380:6379"
      - "16380:16379"
    volumes:
      - redis-node-2-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.3

  redis-node-3:
    image: redis:latest
    container_name: redis-node-3
    command:
      - redis-server
      - --cluster-enabled
      - "yes"
      - --cluster-config-file
      - /data/nodes.conf
      - --cluster-node-timeout
      - "5000"
      - --appendonly
      - "yes"
      - --port
      - "6379"
      - --dir
      - /data
    ports:
      - "6381:6379"
      - "16381:16379"
    volumes:
      - redis-node-3-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.4

  redis-node-4:
    image: redis:latest
    container_name: redis-node-4
    command:
      - redis-server
      - --cluster-enabled
      - "yes"
      - --cluster-config-file
      - /data/nodes.conf
      - --cluster-node-timeout
      - "5000"
      - --appendonly
      - "yes"
      - --port
      - "6379"
      - --dir
      - /data
    ports:
      - "6382:6379"
      - "16382:16379"
    volumes:
      - redis-node-4-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.5

  redis-node-5:
    image: redis:latest
    container_name: redis-node-5
    command:
      - redis-server
      - --cluster-enabled
      - "yes"
      - --cluster-config-file
      - /data/nodes.conf
      - --cluster-node-timeout
      - "5000"
      - --appendonly
      - "yes"
      - --port
      - "6379"
      - --dir
      - /data
    ports:
      - "6383:6379"
      - "16383:16379"
    volumes:
      - redis-node-5-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.6

  redis-node-6:
    image: redis:latest
    container_name: redis-node-6
    command:
      - redis-server
      - --cluster-enabled
      - "yes"
      - --cluster-config-file
      - /data/nodes.conf
      - --cluster-node-timeout
      - "5000"
      - --appendonly
      - "yes"
      - --port
      - "6379"
      - --dir
      - /data
    ports:
      - "6384:6379"
      - "16384:16379"
    volumes:
      - redis-node-6-data:/data
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.7

  redis-cluster-init:
    image: redis:latest
    container_name: redis-cluster-init
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        echo 'Waiting for Redis nodes to be ready...'
        until redis-cli -h redis-node-1 -p 6379 ping >/dev/null 2>&1; do sleep 1; done
        until redis-cli -h redis-node-2 -p 6379 ping >/dev/null 2>&1; do sleep 1; done  
        until redis-cli -h redis-node-3 -p 6379 ping >/dev/null 2>&1; do sleep 1; done
        until redis-cli -h redis-node-4 -p 6379 ping >/dev/null 2>&1; do sleep 1; done
        until redis-cli -h redis-node-5 -p 6379 ping >/dev/null 2>&1; do sleep 1; done
        until redis-cli -h redis-node-6 -p 6379 ping >/dev/null 2>&1; do sleep 1; done
        echo 'All nodes ready. Creating cluster...'
        redis-cli --cluster create 172.20.0.2:6379 172.20.0.3:6379 172.20.0.4:6379 172.20.0.5:6379 172.20.0.6:6379 172.20.0.7:6379 --cluster-replicas 1 --cluster-yes
        echo 'Cluster creation completed'
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data: