using System.Linq;
using System.Text;

namespace ReadUs.SourceGenerators.HashModel;

/// <summary>
/// Emits the companion partial declaration for a <c>[RedisHashModel]</c> type: an
/// <c>IRedisHashModel&lt;T&gt;</c> implementation that maps every mapped property
/// directly to/from a named hash field, with no reflection anywhere — the compiler
/// resolves every member access in the emitted code at compile time, same as any other
/// hand-written C#. See <see cref="HashModelParser"/> for what's classified as
/// mappable and why only two constructor shapes are supported.
/// </summary>
internal static class HashModelEmitter
{
    public static string Emit(HashModelDefinition model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = model.Namespace.Length > 0;
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(model.TypeKeyword).Append(' ').Append(model.TypeName)
          .Append(" : global::ReadUs.Extensions.Hashes.IRedisHashModel<").Append(model.TypeName).AppendLine(">");
        sb.AppendLine("{");

        EmitToHashFields(sb, model);
        sb.AppendLine();
        EmitFromHash(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitToHashFields(StringBuilder sb, HashModelDefinition model)
    {
        sb.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<global::System.ReadOnlyMemory<byte>> ToHashFields()");
        sb.AppendLine("    {");
        sb.AppendLine("        var __fields = new global::System.Collections.Generic.List<global::System.ReadOnlyMemory<byte>>();");

        foreach (var property in model.Properties)
        {
            var clrType = ClrTypeName(property);
            var nameLiteral = CodeGenText.Literal(property.Name);

            if (property.IsNullable)
            {
                // A pattern variable introduced in an `if` condition stays in scope for
                // the rest of the enclosing block, not just that one `if`'s body — a
                // fixed name here would collide across more than one nullable property.
                var localName = "__v" + property.Name;
                sb.Append("        if (this.").Append(property.Name).Append(" is ").Append(clrType).Append(' ').Append(localName).AppendLine(")");
                sb.AppendLine("        {");
                sb.Append("            __fields.Add(global::System.Text.Encoding.UTF8.GetBytes(").Append(nameLiteral).AppendLine("));");
                sb.Append("            __fields.Add(").Append(Encode(property, localName)).AppendLine(");");
                sb.AppendLine("        }");
            }
            else
            {
                sb.Append("        __fields.Add(global::System.Text.Encoding.UTF8.GetBytes(").Append(nameLiteral).AppendLine("));");
                sb.Append("        __fields.Add(").Append(Encode(property, "this." + property.Name)).AppendLine(");");
            }
        }

        sb.AppendLine("        return __fields;");
        sb.AppendLine("    }");
    }

    private static void EmitFromHash(StringBuilder sb, HashModelDefinition model)
    {
        sb.Append("    public static ").Append(model.TypeName).AppendLine(" FromHash(global::ReadUs.Protocol.RedisResult hashReply)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __items = hashReply.AsItems();");

        foreach (var property in model.Properties)
        {
            sb.Append("        ").Append(ClrTypeName(property)).Append("? __").Append(property.Name).AppendLine(" = default;");
        }

        sb.AppendLine("        for (var __i = 0; __i + 1 < __items.Length; __i += 2)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (__items[__i].AsString())");
        sb.AppendLine("            {");
        foreach (var property in model.Properties)
        {
            sb.Append("                case ").Append(CodeGenText.Literal(property.Name)).Append(": __").Append(property.Name)
              .Append(" = ").Append(Decode(property, "__items[__i + 1]")).AppendLine("; break;");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");

        string MissingFieldExpr(string propertyName) => $"__{propertyName} ?? throw new global::System.InvalidOperationException(" +
            $"{CodeGenText.Literal($"Missing required hash field '{propertyName}' while reading '{model.TypeName}'.")})";

        if (model.ConstructionStrategy == HashModelConstructionStrategy.Positional)
        {
            sb.Append("        return new ").Append(model.TypeName).Append('(');
            sb.Append(string.Join(", ", model.ConstructorParameterOrder.Select(p =>
                model.Properties.First(prop => prop.Name == p).IsNullable ? $"__{p}" : MissingFieldExpr(p))));
            sb.AppendLine(");");
        }
        else
        {
            sb.Append("        return new ").Append(model.TypeName).AppendLine();
            sb.AppendLine("        {");
            foreach (var property in model.Properties)
            {
                var valueExpr = property.IsNullable ? $"__{property.Name}" : MissingFieldExpr(property.Name);
                sb.Append("            ").Append(property.Name).Append(" = ").Append(valueExpr).AppendLine(",");
            }

            sb.AppendLine("        };");
        }

        sb.AppendLine("    }");
    }

    private static string ClrTypeName(HashModelProperty property) => property.Kind switch
    {
        HashFieldKind.String => "string",
        HashFieldKind.Bytes => "byte[]",
        HashFieldKind.Int32 => "int",
        HashFieldKind.Int64 => "long",
        HashFieldKind.Double => "double",
        HashFieldKind.Boolean => "bool",
        HashFieldKind.Guid => "global::System.Guid",
        HashFieldKind.DateTime => "global::System.DateTime",
        HashFieldKind.Enum => "global::" + property.EnumTypeName,
        _ => throw new System.InvalidOperationException($"Unreachable: unhandled {nameof(HashFieldKind)}."),
    };

    private static string Encode(HashModelProperty property, string expr) => property.Kind switch
    {
        HashFieldKind.String => $"global::System.Text.Encoding.UTF8.GetBytes({expr})",
        HashFieldKind.Bytes => expr,
        HashFieldKind.Int32 or HashFieldKind.Int64 or HashFieldKind.Double =>
            $"global::System.Text.Encoding.ASCII.GetBytes({expr}.ToString(global::System.Globalization.CultureInfo.InvariantCulture))",
        HashFieldKind.Boolean => $"global::System.Text.Encoding.ASCII.GetBytes({expr} ? \"1\" : \"0\")",
        HashFieldKind.Guid => $"global::System.Text.Encoding.ASCII.GetBytes({expr}.ToString())",
        HashFieldKind.DateTime => $"global::System.Text.Encoding.ASCII.GetBytes({expr}.ToUniversalTime().ToString(\"o\", global::System.Globalization.CultureInfo.InvariantCulture))",
        HashFieldKind.Enum => $"global::System.Text.Encoding.UTF8.GetBytes({expr}.ToString())",
        _ => throw new System.InvalidOperationException($"Unreachable: unhandled {nameof(HashFieldKind)}."),
    };

    private static string Decode(HashModelProperty property, string itemExpr) => property.Kind switch
    {
        HashFieldKind.String => $"{itemExpr}.AsString()",
        HashFieldKind.Bytes => $"{itemExpr}.AsSpan().ToArray()",
        HashFieldKind.Int32 => $"checked((int){itemExpr}.AsInt64())",
        HashFieldKind.Int64 => $"{itemExpr}.AsInt64()",
        HashFieldKind.Double => $"{itemExpr}.AsDouble()",
        HashFieldKind.Boolean => $"{itemExpr}.AsInt64() != 0",
        HashFieldKind.Guid => $"global::System.Guid.Parse({itemExpr}.AsString())",
        HashFieldKind.DateTime => $"global::System.DateTime.Parse({itemExpr}.AsString(), global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.RoundtripKind)",
        HashFieldKind.Enum => $"global::System.Enum.Parse<global::{property.EnumTypeName}>({itemExpr}.AsString())",
        _ => throw new System.InvalidOperationException($"Unreachable: unhandled {nameof(HashFieldKind)}."),
    };
}
