using System.Collections.Generic;
using System.Globalization;
using System.Text;
using ReadUs.SourceGenerators.Model;

namespace ReadUs.SourceGenerators;

/// <summary>
/// Emits the always-present routing/behavior metadata table (project spec §3: "which
/// arguments are keys... which commands are BLOCKING, which are read-only") for every
/// parsed command, regardless of whether it also got a typed method. This is what the
/// Cluster phase (§13 step 5) will consume for slot routing and MOVABLEKEYS/CROSSSLOT
/// validation — it doesn't need to wait for full typed-argument coverage.
/// </summary>
internal static class CommandMetadataEmitter
{
    public static string Emit(IReadOnlyList<CommandDefinition> commands)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace ReadUs.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>One statically-known key range within a command's argument list (project spec §5). <see cref=\"LastKeyPosition\"/> negative means \"relative to the end of the argument list\", matching Redis's own key_specs convention.</summary>");
        sb.AppendLine("public readonly struct GeneratedKeySpec");
        sb.AppendLine("{");
        sb.AppendLine("    public required int FirstKeyPosition { get; init; }");
        sb.AppendLine("    public required int LastKeyPosition { get; init; }");
        sb.AppendLine("    public required int KeyStep { get; init; }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Routing/behavior metadata for one Redis command or subcommand, generated from the vendored command table (project spec §3, codegen/redis-commands/SOURCE.md).</summary>");
        sb.AppendLine("public readonly struct GeneratedCommandInfo");
        sb.AppendLine("{");
        sb.AppendLine("    public required string Name { get; init; }");
        sb.AppendLine("    public string? Container { get; init; }");
        sb.AppendLine("    public required string Group { get; init; }");
        sb.AppendLine("    public required int Arity { get; init; }");
        sb.AppendLine("    public required bool IsWrite { get; init; }");
        sb.AppendLine("    public required bool IsReadOnly { get; init; }");
        sb.AppendLine("    public required bool IsBlocking { get; init; }");
        sb.AppendLine("    public required bool HasUnknownKeys { get; init; }");
        sb.AppendLine("    public required bool HasTypedMethod { get; init; }");
        sb.AppendLine("    public required IReadOnlyList<GeneratedKeySpec> KeySpecs { get; init; }");
        sb.AppendLine("    public string WireCommandName => Container ?? Name;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public static class CommandMetadata");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly IReadOnlyList<GeneratedCommandInfo> All = new GeneratedCommandInfo[]");
        sb.AppendLine("    {");

        foreach (var command in commands)
        {
            sb.Append("        new() { Name = ").Append(Literal(command.Name));
            sb.Append(", Container = ").Append(command.Container is null ? "null" : Literal(command.Container));
            sb.Append(", Group = ").Append(Literal(command.Group));
            sb.Append(", Arity = ").Append(command.Arity.ToString(CultureInfo.InvariantCulture));
            sb.Append(", IsWrite = ").Append(Bool(command.IsWrite));
            sb.Append(", IsReadOnly = ").Append(Bool(command.IsReadOnly));
            sb.Append(", IsBlocking = ").Append(Bool(command.IsBlocking));
            sb.Append(", HasUnknownKeys = ").Append(Bool(command.HasUnknownKeys));
            sb.Append(", HasTypedMethod = ").Append(Bool(command.Parameters is not null));
            sb.Append(", KeySpecs = new GeneratedKeySpec[] { ");
            foreach (var spec in command.KeySpecs)
            {
                sb.Append("new() { FirstKeyPosition = ").Append(spec.FirstKeyPosition.ToString(CultureInfo.InvariantCulture));
                sb.Append(", LastKeyPosition = ").Append(spec.LastKeyPosition.ToString(CultureInfo.InvariantCulture));
                sb.Append(", KeyStep = ").Append(spec.KeyStep.ToString(CultureInfo.InvariantCulture));
                sb.Append(" }, ");
            }

            sb.Append("} },");
            sb.AppendLine();
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Shared by every generated typed command method (see TypedMethodEmitter) to turn a scalar argument into wire bytes.</summary>");
        sb.AppendLine("internal static class ArgumentEncoding");
        sb.AppendLine("{");
        sb.AppendLine("    public static ReadOnlyMemory<byte> EncodeInteger(long value) => System.Text.Encoding.ASCII.GetBytes(value.ToString(System.Globalization.CultureInfo.InvariantCulture));");
        sb.AppendLine("    public static ReadOnlyMemory<byte> EncodeDouble(double value) => System.Text.Encoding.ASCII.GetBytes(value.ToString(System.Globalization.CultureInfo.InvariantCulture));");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Literal(string value) => CodeGenText.Literal(value);
}
