using System.Collections.Generic;
using System.Linq;
using System.Text;
using ReadUs.SourceGenerators.Model;

namespace ReadUs.SourceGenerators;

/// <summary>
/// Emits one <c>RedisClient</c> extension method per command whose argument shape
/// <see cref="CommandTableParser"/> could flatten, grouped into one static class per
/// command <c>group</c> (project spec §3: "grouped by data type"). See
/// <see cref="CommandTableParser"/>'s remarks for exactly which shapes qualify.
/// </summary>
internal static class TypedMethodEmitter
{
    public static string EmitGroup(string group, IReadOnlyList<CommandDefinition> commands)
    {
        var tokens = new TokenFieldCollector();
        var methodsSb = new StringBuilder();

        foreach (var command in commands)
        {
            EmitMethod(methodsSb, command, tokens);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ReadUs;");
        sb.AppendLine("using ReadUs.Protocol;");
        sb.AppendLine();
        sb.AppendLine("namespace ReadUs.Generated;");
        sb.AppendLine();
        sb.Append("public static class ").Append(NameHelpers.GroupClassName(group)).AppendLine();
        sb.AppendLine("{");

        foreach (var field in tokens.Fields)
        {
            sb.Append("    private static readonly ReadOnlyMemory<byte> ").Append(field.Value)
              .Append(" = ").Append(Utf8BytesLiteral(field.Key)).AppendLine(";");
        }

        sb.Append(methodsSb);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, CommandDefinition command, TokenFieldCollector tokens)
    {
        string methodName = NameHelpers.MethodName(command);
        string wireNameField = tokens.GetOrAdd(command.WireCommandName);

        var decls = new List<(string Declaration, bool Optional)>();
        var body = new List<string> { "var __wireArgs = new List<ReadOnlyMemory<byte>>();" };

        if (command.Container is not null)
        {
            string subcommandField = tokens.GetOrAdd(command.Name);
            body.Add($"__wireArgs.Add({subcommandField});");
        }

        foreach (var slot in command.Parameters!)
        {
            switch (slot)
            {
                case CommandArgument arg:
                    EmitArgument(arg, tokens, decls, body);
                    break;
                case CommandArgumentGroup group:
                    EmitGroup(group, tokens, decls, body);
                    break;
            }
        }

        // C# requires required parameters before optional ones; the vendored table's
        // own argument order (preserved for wire emission in `body` above) doesn't
        // always already satisfy that, so the declaration list is partitioned here —
        // this never affects wire order, only the signature.
        var orderedDecls = decls.Where(d => !d.Optional).Select(d => d.Declaration)
            .Concat(decls.Where(d => d.Optional).Select(d => d.Declaration))
            .Append("CancellationToken cancellationToken = default");

        string dispatch = command.IsBlocking ? "ExecuteBlockingAsync" : "ExecuteAsync";

        sb.AppendLine();
        sb.Append("    public static ValueTask<RedisResult> ").Append(methodName)
          .Append("(this RedisClient client, ").Append(string.Join(", ", orderedDecls)).AppendLine(")");
        sb.AppendLine("    {");
        foreach (var line in body)
        {
            sb.Append("        ").AppendLine(line);
        }

        sb.Append("        return client.").Append(dispatch).Append('(').Append(wireNameField).Append(", __wireArgs.ToArray(), cancellationToken);").AppendLine();
        sb.AppendLine("    }");
    }

    private static void EmitArgument(CommandArgument arg, TokenFieldCollector tokens, List<(string, bool)> decls, List<string> body)
    {
        string paramName = NameHelpers.SanitizeIdentifier(NameHelpers.ParameterIdentifier(arg.Name));
        string? tokenField = arg.Token is null ? null : tokens.GetOrAdd(arg.Token);

        if (arg.WireType == ArgumentWireType.PureToken)
        {
            decls.Add(($"bool {paramName} = false", true));
            body.Add($"if ({paramName}) {{ __wireArgs.Add({tokenField}); }}");
            return;
        }

        string netType = NameHelpers.DotNetTypeName(arg.WireType);

        string Encode(string expr) => arg.WireType switch
        {
            ArgumentWireType.Integer => $"ArgumentEncoding.EncodeInteger({expr})",
            ArgumentWireType.Double => $"ArgumentEncoding.EncodeDouble({expr})",
            _ => expr,
        };

        if (arg.Multiple)
        {
            bool optional = arg.Optional;
            string arrType = optional ? $"{netType}[]?" : $"{netType}[]";
            decls.Add(($"{arrType} {paramName}" + (optional ? " = null" : string.Empty), optional));

            var loopLines = new List<string>();
            if (tokenField is not null && !arg.MultipleToken)
            {
                loopLines.Add($"if ({paramName}.Length > 0) {{ __wireArgs.Add({tokenField}); }}");
            }

            string perItemToken = tokenField is not null && arg.MultipleToken ? $"__wireArgs.Add({tokenField}); " : string.Empty;
            loopLines.Add($"foreach (var item in {paramName}) {{ {perItemToken}__wireArgs.Add({Encode("item")}); }}");

            if (optional)
            {
                body.Add($"if ({paramName} is not null) {{");
                foreach (var line in loopLines)
                {
                    body.Add("    " + line);
                }

                body.Add("}");
            }
            else
            {
                body.AddRange(loopLines);
            }

            return;
        }

        if (arg.Optional)
        {
            decls.Add(($"{netType}? {paramName} = null", true));
            var lines = new List<string> { $"if ({paramName}.HasValue) {{" };
            if (tokenField is not null)
            {
                lines.Add($"    __wireArgs.Add({tokenField});");
            }

            lines.Add($"    __wireArgs.Add({Encode($"{paramName}.Value")});");
            lines.Add("}");
            body.AddRange(lines);
        }
        else
        {
            decls.Add(($"{netType} {paramName}", false));
            if (tokenField is not null)
            {
                body.Add($"__wireArgs.Add({tokenField});");
            }

            body.Add($"__wireArgs.Add({Encode(paramName)});");
        }
    }

    private static void EmitGroup(CommandArgumentGroup group, TokenFieldCollector tokens, List<(string, bool)> decls, List<string> body)
    {
        string paramName = NameHelpers.SanitizeIdentifier(NameHelpers.ParameterIdentifier(group.Name));
        string? tokenField = group.Token is null ? null : tokens.GetOrAdd(group.Token);

        string tupleType = "(" + string.Join(", ", group.Members.Select(m =>
            $"{NameHelpers.DotNetTypeName(m.WireType)} {NameHelpers.TupleElementName(m.Name)}")) + ")";

        string EncodeMember(CommandArgument member, string accessor) => member.WireType switch
        {
            ArgumentWireType.Integer => $"ArgumentEncoding.EncodeInteger({accessor})",
            ArgumentWireType.Double => $"ArgumentEncoding.EncodeDouble({accessor})",
            _ => accessor,
        };

        if (group.Multiple)
        {
            bool optional = group.Optional;
            string listType = optional ? $"IReadOnlyList<{tupleType}>?" : $"IReadOnlyList<{tupleType}>";
            decls.Add(($"{listType} {paramName}" + (optional ? " = null" : string.Empty), optional));

            var addLines = new List<string>();
            if (tokenField is not null)
            {
                addLines.Add($"__wireArgs.Add({tokenField});");
            }

            for (int i = 0; i < group.Members.Count; i++)
            {
                addLines.Add($"__wireArgs.Add({EncodeMember(group.Members[i], $"item.Item{i + 1}")});");
            }

            string loop = $"foreach (var item in {paramName}) {{ {string.Join(" ", addLines)} }}";
            body.Add(optional ? $"if ({paramName} is not null) {{ {loop} }}" : loop);
            return;
        }

        // Non-multiple groups are only ever optional — a required, fixed, non-repeating
        // block is inlined by CommandTableParser and never reaches this method.
        decls.Add(($"{tupleType}? {paramName} = null", true));

        var innerLines = new List<string>();
        if (tokenField is not null)
        {
            innerLines.Add($"__wireArgs.Add({tokenField});");
        }

        for (int i = 0; i < group.Members.Count; i++)
        {
            innerLines.Add($"__wireArgs.Add({EncodeMember(group.Members[i], $"{paramName}.Value.Item{i + 1}")});");
        }

        body.Add($"if ({paramName}.HasValue) {{ {string.Join(" ", innerLines)} }}");
    }

    private static string Utf8BytesLiteral(string value) => CodeGenText.Literal(value) + "u8.ToArray()";

    private sealed class TokenFieldCollector
    {
        private readonly Dictionary<string, string> _fieldsByValue = new();
        private readonly HashSet<string> _usedNames = new();

        public IEnumerable<KeyValuePair<string, string>> Fields => _fieldsByValue;

        public string GetOrAdd(string tokenValue)
        {
            if (_fieldsByValue.TryGetValue(tokenValue, out string? existing))
            {
                return existing;
            }

            string baseName = NameHelpers.WireNameFieldName(NameHelpers.SanitizeIdentifier(tokenValue));
            string name = baseName;
            int suffix = 1;
            while (!_usedNames.Add(name))
            {
                name = baseName + (++suffix).ToString(System.Globalization.CultureInfo.InvariantCulture);
            }

            _fieldsByValue[tokenValue] = name;
            return name;
        }
    }
}
