name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@v2       

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore Dependencies (ReadUs)
      run: dotnet restore ./ReadUs/ReadUs.csproj

    - name: Restore Dependencies (ReadUs.Tests)
      run: dotnet restore ./ReadUs.Tests/ReadUs.Tests.csproj

    - name: Build ReadUs
      run: dotnet build ./ReadUs/ReadUs.csproj --no-restore

    - name: Build ReadUs.Tests
      run: dotnet build ./ReadUs.Tests/ReadUs.Tests.csproj --no-restore

    - name: Test
      run: dotnet test --no-build
    